version: "3.3"

services:
  bitnami:
    image: bitnami/nginx:1.21
    ports:
        - 8083:8080
    volumes:
        - ./build:/app:ro
#   nginx:
#     image: nginx:1.21-alpine
#     ports:
#         - 8082:80
#     volumes:
#         - ./build:/app:ro
#         - ./cache:/var/cache/nginx:rw
#         - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
#   static-web-server:
#     image: joseluisq/static-web-server:2.0.0-beta.5
#     environment:
#         - SERVER_HOST=0.0.0.0
#         - SERVER_PORT=80
#         - SERVER_ROOT=/public
#     ports:
#         - 8080:80
#     volumes:
#         - ./build:/public:ro
#   gostatic:
#     image: pierrezemb/gostatic
#     command:
#         - -port 
#         - "80"
#     ports:
#         - 8081:80
#     volumes:
#         - ./build:/srv/http:ro