apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "react-app.fullname" . }}-download-script
  labels:
    {{- include "react-app.labels" . | nindent 4 }}
data:
  download.sh: |
    #!/bin/sh

    # set -euo pipefail

    echo CI_PROJECT_URL=${CI_PROJECT_URL}
    echo GITLAB_URL=${GITLAB_URL}
    echo CI_PROJECT_NAME=${CI_PROJECT_NAME}
    echo GITLAB_JOB_TOKEN=${GITLAB_JOB_TOKEN}
    echo GITLAB_PROJECT_ID=${GITLAB_PROJECT_ID}
    echo GITLAB_JOB_ID=${GITLAB_JOB_ID}

    echo && echo "Processing..." && echo

    curl  --silent --output /tmp/artifacts.zip \
          --header "PRIVATE-TOKEN: ${GITLAB_JOB_TOKEN}" \
          "${GITLAB_URL}/api/v4/projects/${GITLAB_PROJECT_ID}/jobs/${GITLAB_JOB_ID}/artifacts"

    if [ "$?" -ne "0" ]; then
      echo "Can't download"
      exit 1
    fi
    
    unzip /tmp/artifacts.zip -d /tmp -q -o
    
    if [ "$?" -ne "0" ]; then
      echo "Can't unzip 'artifacts.zip'. Archive content:"
      head /tmp/artifacts.zip && echo
      exit 1
    fi

    rm -rf /tmp/build/ci_*
    mv /tmp/build/* /app

    echo "---------------------"
    ls -alh /app
    echo "---------------------"

    echo && echo "Success!"
