{{- if .Values.nginx.configCreate -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "react-app.fullname" . }}-nginx-config
  labels:
    {{- include "react-app.labels" . | nindent 4 }}
data:
  default.conf: |
    location / {
        error_page 404 =200 /index.html;
        root /app;
        try_files $uri $uri/ /index.html?$args;

        # kill cache
        add_header Last-Modified $date_gmt;
        add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
        if_modified_since off;
        expires off;
        etag off;
        sendfile off;
    }
    # Do not cache sw.js, required for offline-first updates.
    location /sw.js {
        alias /app/sw.js;
        add_header Cache-Control "no-cache";
        proxy_cache_bypass $http_pragma;
        proxy_cache_revalidate on;
        expires off;
        access_log off;
        error_log off;
    }
{{- end }}
