apiVersion: v1
kind: Service
metadata:
  name: {{ include "react-app.fullname" . }}
  labels:
    {{- include "react-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port | default 80 }}
      targetPort: {{ .Values.container.port | default 80 }}
      protocol: {{ .Values.service.protocol | default "TCP" }}
      name: {{ .Values.service.portName | default "http" }}
  selector:
    {{- include "react-app.selectorLabels" . | nindent 4 }}
